[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rcli"
version = "1.0.0"
dependencies = [
    "docopt>=0.6.2"
]

[project.scripts]
rcli = "rcli:main"
